console.log("***Assignment 18***");
  const friends = ["NewYork","Houston", "Dubai", "Abu Dhabi","Tornoto"];
  console.log(friends);
  console.log("Alphabetical Order");
  const fsort = []; 
  fsort.push(friends);
  console.log(friends.sort());
  console.log("Original List");
  console.log(fsort);
  console.log("Reverse Order");
  const rsort = []; 
   rsort.push(fsort);
 console.log(friends.reverse());
 console.log("Original List");
 console.log(rsort);